function [fitresult, gof] = createFit(curve2, curve1)
%CREATEFIT(CURVE2,CURVE1)
% Copyright (C) 2020 Tomppa Pakarinen, tomppa.pakarinen@tuni.fi


% This program is free software: you can redistribute it and/or modify it 
% under the terms of the GNU General Public License as published by the  
% Free Software Foundation, either version 3 of the License, or (at your 
% option) any later version.
%
% This program is distributed in the hope that it will be useful, but 
% WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General 
% Public License for more details.
% 
% You should have received a copy of the GNU General Public License along 
% with this program. If not, see http://www.gnu.org/licenses/


%  Create a fit.
%
%  Data for 'tempcurvefit' fit:
%      X Input : curve2
%      Y Output: curve1
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 03-Nov-2020 00:45:44


%% Fit: 'tempcurvefit'.
[xData, yData] = prepareCurveData(curve2, curve1);

% Set up fittype and options.
ft = 'poly3';

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
%figure( 'Name', 'tempcurvefit' );
%h = plot( fitresult, xData, yData );
%legend( h, 'curve1 vs. curve2', 'tempcurvefit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
%xlabel( 'curve2', 'Interpreter', 'none' );
%ylabel( 'curve1', 'Interpreter', 'none' );
%grid on


